name: CI Pipeline 

on:
  push:
    branches:
        - main
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout code
         uses: actions/checkout@v4  

       - name: Set up node.js
         uses: actions/setup-node@v4  
         with: 
            node-version: '18'
       
       - name: Install dependencies
         run: npm install 

       - name: Login to Github Container Registry
         uses: docker/login-action@v3
         with: 
           registry: ghcr.io 
           username: ${{ github.actor }} 
           password: ${{ secrets.GHCR_TOKEN }} 

       - name: Convert username to lowercase 
         run: |
          USERNAME=${{ github.repository_owner }} 
          USERNAME_LC=$(echo "$USERNAME" | tr '[:upper:]' '[:lower:]') 
          echo "USERNAME_LC=$USERNAME_LC" >> $GITHUB_ENV

       - name: Build and push Docker image
         uses: docker/build-push-action@v5 
         with:
            context: .
            push: true 
            tags: ghcr.io/${{ env.USERNAME_LC }}/myapp:v1 
       
      